[files]
extend-exclude = [
    "package.json",
    "package-lock.json",
    "*.svg",
    "localstorage/**",
    "node_modules/**",
    "matrix-art-db/**",
    ".next/**"
]

[default]
locale = "en"

[default.extend-words]
ND = "ND"