name: Fossa Scan
permissions: read-all
on:
  push:
    branches: [main]
jobs:
  fossa-scan:
    runs-on: self-hosted
    steps:
      # - name: Harden Runner
      #   uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4 # v1
      #   with:
      #     allowed-endpoints: "
      #       app.fossa.com:443
      #       github.com:443
      #       objects.githubusercontent.com:443
      #       raw.githubusercontent.com:443"
      #   env:
      #     USER: runner
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - uses: fossas/fossa-action@88bec1fd3c4652f3929fdde3774eae9e9fcdb6ee # main
        with:
          api-key: ${{secrets.fossaApiKey}}
