name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
        with:
          egress-policy: audit
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps && npx playwright install msedge
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        if: always()
        with:
          name: playwright-test-results
          path: test-results/
