name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions: read-all

jobs:
  test:
    permissions:
      contents: read # for actions/checkout to fetch code
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
      # - name: Harden Runner
      #   uses: step-security/harden-runner@bdb12b622a910dfdc99a31fdfe6f45a16bc287a4 # v1
      #   with:
      #     allowed-endpoints: "
      #       github.com:22
      #       github.com:443
      #       api.github.com:443
      #       nodejs.org:443
      #       registry.npmjs.org:443
      #       playwright.azureedge.net:443
      #       azure.archive.ubuntu.com:443
      #       azure.archive.ubuntu.com:80
      #       security.ubuntu.com:80
      #       packages.microsoft.com:80
      #       packages.microsoft.com:443
      #       ppa.launchpad.net:80
      #       fonts.googleapis.com:443
      #       telemetry.nextjs.org:443
      #       location.services.mozilla.com:443
      #       art.midnightthoughts.space:443
      #       matrix.art.midnightthoughts.space:443
      #       localhost:80"
      #   env:
      #     USER: runner
      - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
        with:
          persist-credentials: false
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v2
        with:
          node-version: "17.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps && npx playwright install msedge && npx playwright install chrome
      - name: Run Playwright tests
        run: npm run test
      - uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535 # v2
        if: always()
        with:
          name: playwright-test-results
          path: test-results/
