name: Spell Check
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
        with:
          egress-policy: block
          allowed-endpoints: github.com:443
      - name: Checkout Actions Repository
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2

      - name: Check spelling
        uses: crate-ci/typos@4b2e66487c0d94e0f0ab1765a9e74bfed663aa1e # master
        with:
          config: ${{github.workspace}}/_typos.toml
